ログインログアウト機能実装
shinonome-inc/backend-final-assignment-Kosei-Arakida-Kosei pull request #2
Opened 2023-04-23 02:04 UTC by Kosei2002

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-23 03:29 UTC, kotasuzuki72 requested changes

2023-04-23 03:29 UTC, kotasuzuki72 commented on accounts/views.py
> +class LogoutView(LoginRequiredMixin, LogoutView):
LogoutViewにおいて、`LoginRequiredMixin`は継承しても良いですが、必須ではないことをコメントしておきます。

2023-04-23 03:29 UTC, kotasuzuki72 commented on accounts/views.py
> +    template_name = "accounts/login.html"
importしたLoginViewの名称が被ってしまっています。
よって、accounts/views.pyの4行目を
`from django.contrib.auth import views as auth_views`
のようにimportし、同ファイル30行目を
`class LoginView(auth_views.LoginView)`
のようにしてください。
このように変更すると、名称が被りません。

2023-04-23 03:29 UTC, kotasuzuki72 commented on accounts/views.py
> +class LogoutView(LoginRequiredMixin, LogoutView):
こちらも名称変更の必要があります。

2023-04-23 03:48 UTC, kotasuzuki72 approved these changes
LGTM

2023-04-24 08:18 UTC, sui-false requested changes
おおむねよく書けていると思います！
classを使わなくても作れるviewはたしかここだけなので、書いてみましょう！

2023-04-24 08:18 UTC, sui-false commented on accounts/views.py
> +    pass
見たところ、何も処理していないようなので、わざわざclassで書かなくて良いと思います。
classを使わないで書いてみましょう

2023-04-26 11:21 UTC, sui-false requested changes

2023-04-26 11:21 UTC, sui-false commented on accounts/views.py
> +class LoginView(auth_views.LoginView):
こちらもこれだけなら、クラスで書く必要はないと思うので、Logoutと書き方を揃えましょう！

2023-04-27 00:26 UTC, sui-false requested changes

2023-04-27 00:26 UTC, sui-false commented on accounts/views.py
> +class LoginView(auth_views.LoginView):
urls.pyに書いたので、こっちは消してしまいましょう

2023-04-29 01:23 UTC, sui-false approved these changes

2023-04-29 01:24 UTC, merged